version: '2.2'

services: 
    source:
        build:
            context: .
            dockerfile: ./dockerfile
        container_name: "go-simple-mvc"
        working_dir: /go-simple-mvc
        restart: always
        ports:
            - 8080:8080
        command: "./go-simple-mvc"