# build stage
FROM golang:1.16.3-alpine as builder
ENV GO111MODULE="on"
ENV CGO_ENABLED=0
WORKDIR /app
COPY . /app
RUN go build -o app

# final stage
FROM alpine
WORKDIR /app
COPY --from=builder /app /app