version: '2.2'

services:
  source:
    build:
      context: .
      dockerfile: ./dockerfile_multiple_build
    container_name: "go-simple-mvc"
    working_dir: /app
    restart: always
    ports:
      - 8080:8080
    command: "./app"
